version: '3.2'
services:
  relay:
    container_name: webhookrelay
    image: webhookrelay/webhookrelayd:latest
    restart: always
    environment:
      # Authentication
      - RELAY_KEY=c9b92031-2df1-4c2e-be3c-0a1b99ea3205
      - RELAY_SECRET=uvp68sKCYFzY
      # buckets list to subscribe
      - BUCKETS=arqan-jenkins

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    restart: always
    privileged: true
    user: root
    ports:
      - 9999:8080
      - 50000:50000
    volumes:
      - /var/lib/docker/volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    